{% set version = "1.1-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-arrayhelpers
  version: {{ version|replace("-", "_") }}

source:
  fn: arrayhelpers_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/arrayhelpers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/arrayhelpers/arrayhelpers_{{ version }}.tar.gz
  sha256: 5fddd5dd4fb8237bcb24465ef823bc8715ba53e6e5fd7a716c31c48ec128340b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-svunit
  run:
    - r-base
    - r-svunit

test:
  commands:
    - $R -e "library('arrayhelpers')"           # [not win]
    - "\"%R%\" -e \"library('arrayhelpers')\""  # [win]

about:
  home: http://arrayhelpers.r-forge.r-project.org/
  license: GPL2
  summary: Some convenient functions to work with arrays.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
