appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: sJfgJxVD16uFAtTuYwuZqhrR1PyVu7S4eo27PH0DlEHsD1+xaiOOTvtCkdprYtuwncROonEV0BnhPNcKMx6QEIREmFVikEtdoGkWim0CbU4hUneGZRBYXts31sua4tbP1orWxSPZ1YP5B7iwY6LCEoKZm20OsukWmwEprqh4lvtPt5ufBPc7494bJJMfkwOM5MYFxs8pQIdDeB81Nsvs0kfK731MUhPRudz9lOPwqjLY5rXm7WoplJAqK7TvucyS5aLfSZcCdzr/nrqG40uj/9XGBG72IZHvXnaygOlj0iqhsLTaWOu9DQEoY+itv00jS5rCrNC7+KjzCS2sxPGbW97L0DtaMCvVifs8fCQX2YglsMy+3fT1u6oSUxELKImz/msvyvbkp/a/SHjSLawGa9ud2D1M3VEefOyA2r8oJ7XtwvCxAcfkb7wXheOnFHYjxHpS/SHcA6uzj+2pBe/ASbeepX/myTcMaKopT/XQ3J/+3OZOChlanH7/gGooigtNIuHIp66gynPWYev//dAkUCJywfNFdTCDX75sdR8Y9/iWo2b9NMPJx8XauaCsIVdtdEyDPaKge1K4kp+6DiTcLq/jWQ1odTIVRRTdY9f39ev+b/gPrblfMhednkh0gOo0WD1eA//6Rk2rV0YH/xdsVOdd06RGd3bEtO1cG4hEouE=}
